# Generated by Django 3.2.7 on 2021-10-03 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classCode', models.CharField(max_length=20)),
                ('courseNumber', models.CharField(max_length=8)),
                ('section', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('units', models.SmallIntegerField()),
                ('level', models.SmallIntegerField()),
                ('startDate', models.DateField(verbose_name='start date')),
                ('endDate', models.DateField(verbose_name='end date')),
                ('defaultStartTime', models.TimeField(verbose_name='default start time')),
                ('defaultEndTime', models.TimeField(verbose_name='default start time')),
                ('irregularTimes', models.SmallIntegerField(choices=[(1, 'Irregular Time'), (0, 'Regular Time')])),
                ('dow', models.CharField(max_length=7)),
                ('ohtime', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('courseNotes', models.TextField()),
                ('descriptionAssignment', models.TextField()),
                ('evalInfo', models.TextField()),
                ('instructorBio', models.TextField()),
                ('askCopy', models.SmallIntegerField(choices=[(1, 'Is Ask Copy'), (0, 'Not Ask Copy')])),
                ('priorCourseId', models.IntegerField()),
                ('programId', models.IntegerField()),
                ('semesterId', models.IntegerField()),
                ('hasBeenEdited', models.SmallIntegerField(choices=[(1, 'Edited'), (0, 'Not Edited')])),
                ('gradingBreakDown', models.TextField()),
                ('useCondensedSchedule', models.SmallIntegerField(choices=[(1, 'Use'), (0, 'Not Use')])),
                ('templateId', models.IntegerField()),
                ('extraFields', models.TextField()),
                ('programYear', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('USStatus', models.SmallIntegerField()),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('cityStateZip', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('active', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Not Active')])),
                ('vendorNumber', models.CharField(max_length=12)),
                ('homeDepartment', models.IntegerField()),
                ('fullTime', models.SmallIntegerField()),
                ('tenureStatus', models.SmallIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('limitedEngagementEligible', models.SmallIntegerField(choices=[(1, 'Eligible'), (0, 'Not Eligible')])),
                ('academicRank', models.CharField(max_length=100)),
                ('instructorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor_course_API.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', models.SmallIntegerField(choices=[(0, 'Coordinator'), (1, 'Instructor')])),
                ('eval', models.SmallIntegerField(choices=[(1, 'Evaluator'), (0, 'Not Evaluator')])),
                ('officeHours', models.TextField()),
                ('preferredContact', models.TextField()),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor_course_API.course')),
                ('instructorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor_course_API.instructorappointment')),
            ],
        ),
    ]
