# Generated by Django 3.2.7 on 2021-10-03 07:47

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_course_API', '0002_auto_20211003_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='defaultEndTime',
            field=models.TimeField(verbose_name='default end time'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('startDate__lte', django.db.models.expressions.F('endDate'))), name='correct_date'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(check=models.Q(('defaultStartTime__lte', django.db.models.expressions.F('defaultEndTime'))), name='correct_time'),
        ),
    ]
