# Generated by Django 3.2.7 on 2021-10-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_course_API', '0003_auto_20211003_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='priorCourseId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructor_course_API.course'),
        ),
    ]
