# Generated by Django 3.2.7 on 2021-10-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor_course_API', '0006_auto_20211004_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='defaultEndTime',
            field=models.TimeField(blank=True, null=True, verbose_name='default end time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='defaultStartTime',
            field=models.TimeField(blank=True, null=True, verbose_name='default start time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='programYear',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='courseinstructor',
            name='eval',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Evaluator'), (0, 'Not Evaluator')], null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='USStatus',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructorappointment',
            name='vendorNumber',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
